import type { DemoCase, DemoPost, DemoService, DemoQuote } from "@/types/agency";
export type { DemoCase, DemoPost, DemoService, DemoQuote };

/**
 * Sample content so the Work and Journal pages look finished immediately,
 * before you've added anything in the admin panel. As soon as you publish real
 * case studies / posts, they take over and this is ignored automatically.
 *
 * The detail pages fall back to these when a slug isn't found in the database,
 * so every sample card is fully clickable.
 */

export const demoCases: DemoCase[] = [
  {
    slug: "northwind-commerce",
    title: "A storefront that loads in under a second",
    client_name: "Northwind",
    industry: "E-commerce",
    year: "2025",
    outcome: "Rebuilt a slow Shopify store into a headless storefront. Conversion up 41%.",
    challenge:
      "Northwind's store took six seconds to load on mobile and lost most visitors before the page even appeared. Checkout abandonment was brutal, and the team couldn't update content without a developer.",
    solution:
      "We moved them to a headless setup — a fast custom front end with Shopify handling orders behind the scenes. Content became editable in a simple CMS, images were optimised automatically, and checkout dropped to two steps.",
    services: ["Web development", "E-commerce", "Analytics & CRO"],
    tech_stack: ["Next.js", "Shopify", "TypeScript", "Tailwind", "Vercel"],
    metrics: [
      { label: "Load time", value: "0.9s" },
      { label: "Conversion", value: "+41%" },
      { label: "Bounce rate", value: "−28%" },
    ],
    live_url: "https://example.com",
  },
  {
    slug: "kavi-health",
    title: "A booking app patients actually finish",
    client_name: "Kavi Health",
    industry: "Healthcare",
    year: "2025",
    outcome: "A cross-platform app that cut no-shows by a third with smart reminders.",
    challenge:
      "Kavi's patients booked by phone, which meant missed calls, double bookings and a receptionist buried in admin. No-shows were costing real money every week.",
    solution:
      "One app for iOS and Android from a single codebase. Patients book in three taps, get reminders they can't miss, and reschedule themselves. The clinic sees everything on a live dashboard.",
    services: ["Mobile apps", "UI/UX", "Custom software"],
    tech_stack: ["React Native", "Supabase", "Node", "Figma"],
    metrics: [
      { label: "No-shows", value: "−34%" },
      { label: "Bookings/mo", value: "2.1k" },
      { label: "App rating", value: "4.8★" },
    ],
    live_url: "https://example.com",
  },
  {
    slug: "vertex-growth",
    title: "From invisible to page one in ninety days",
    client_name: "Vertex",
    industry: "B2B SaaS",
    year: "2024",
    outcome: "A technical SEO overhaul that tripled organic traffic in one quarter.",
    challenge:
      "Vertex had a good product nobody could find. Their site was technically broken for search engines, content was thin, and paid ads were their only channel — expensive and fragile.",
    solution:
      "We fixed the technical foundation, restructured the content around what buyers actually search, and built a publishing rhythm. Organic became their biggest channel within a quarter.",
    services: ["SEO", "Content & copywriting", "Analytics & CRO"],
    tech_stack: ["Next.js", "GA4", "Ahrefs", "Search Console"],
    metrics: [
      { label: "Organic traffic", value: "3.2×" },
      { label: "Ranking keywords", value: "+480" },
      { label: "Cost per lead", value: "−52%" },
    ],
    live_url: "https://example.com",
  },
];

export const demoPosts: DemoPost[] = [
  {
    slug: "why-we-write-scope-first",
    title: "Why we write the scope before we write any code",
    excerpt:
      "The single habit that has saved more projects than any tool or framework: agreeing, in writing, exactly what's being built before starting.",
    tags: ["Process", "Working with us"],
    read_minutes: 6,
    published_at: "2026-01-15",
    cover_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
    content:
      "Most project disputes aren't about code quality — they're about expectation mismatch. The client pictured a multi-tenant dashboard with custom permissions; the agency built a standard admin panel. Nobody wrote down the specifics, and both sides ended up frustrated.\n\nAt Nex Desk, we write the scope first: every single deliverable, every explicit exclusion, the exact price, the timeline, and the number of revision rounds included. You review and sign it before an editor ever opens.\n\n## The Scope Document: A Shared Contract\n\nWriting scope feels slow to agencies that want to get moving immediately. In practice, it is the fastest way to build software because it eliminates the mid-project friction that stalls delivery.\n\nOur scope documents explicitly define:\n- Exact page layouts and component specifications\n- Technical integrations (payment gateways, CMS, authentication)\n- Non-functional targets (load speed, Lighthouse score thresholds, browser support)\n- Out-of-scope items so there are no midnight surprises\n\n## How Scope Protects Your Budget\n\nWhen scope is vague, changes are handled awkwardly. Either the agency eats the cost and builds resentment, or you get slapped with surprise invoices at handover.\n\nWith a clear scope document, any request outside the initial agreement triggers a transparent change order: a short PDF specifying the additional cost and timeline adjustment. You stay in 100% control of your budget at every step.\n\n## The Handover Guarantee\n\nOnce the final milestone is reached, we check off every deliverable against the original scope document. You get a signed handover agreement PDF certifying that everything promised was delivered, along with full ownership transfers for your codebase and accounts.",
  },
  {
    slug: "fast-websites-are-a-feature",
    title: "A fast website is a feature, not a nice-to-have",
    excerpt:
      "Every second your site takes to load costs you visitors. Here's how we get real projects under a second, and why it pays for itself.",
    tags: ["Performance", "Web"],
    read_minutes: 7,
    published_at: "2026-01-08",
    cover_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    content:
      "Load speed isn't vanity — it is directly tied to revenue. Industry research consistently proves that over 53% of mobile visitors abandon a site if it takes longer than three seconds to load. On standard 4G connections, many bloated agency sites routinely take six seconds or longer.\n\nWhen we build web applications at Nex Desk, speed is treated as a core feature of the product, not an afterthought left for a post-launch cleanup.\n\n## The Financial Impact of Load Speed\n\nA one-second delay in page load time reduces conversion rates by up to 20%. If your store or service site turns over $10,000 a month, a slow front end is silently costing you thousands in leaked revenue.\n\nKey speed metrics search engines and users evaluate:\n- Largest Contentful Paint (LCP): How quickly main content appears (Target: < 1.2s)\n- First Input Delay (FID) / INP: How fast the page responds to clicks (Target: < 50ms)\n- Cumulative Layout Shift (CLS): Visual stability as elements load (Target: 0)\n\n## Technical Architecture for Sub-Second Speed\n\nWe achieve sub-second speeds by making smart engineering choices from day one:\n- Server-side rendering (SSR) and static generation with Next.js\n- Automatic image optimization, WebP conversion, and responsive srcset attributes\n- Eliminating heavy client-side libraries and unnecessary third-party tracking scripts\n- Edge caching assets globally via high-speed CDNs\n\n## Our 90+ Lighthouse Guarantee\n\nWe treat a 90+ score on Google Lighthouse as the floor, not an ambitious goal. Before any website goes live on your domain, we run automated performance audits across mobile and desktop viewpoints to ensure your site is fast out of the gate.",
  },
  {
    slug: "own-your-code",
    title: "You should own your code. All of it.",
    excerpt:
      "Lock-in is a business model for agencies and a trap for clients. Here's why we hand over everything, every time.",
    tags: ["Working with us", "Ownership"],
    read_minutes: 5,
    published_at: "2025-12-20",
    cover_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
    content:
      "Vendor lock-in is one of the dirtiest secrets in the agency business. Some agencies keep your source code in private repositories, hold your domain registrar hostage, or build on proprietary internal drag-and-drop engines so you can never leave without rebuilding from scratch.\n\nAt Nex Desk, we do the complete opposite: on final payment, 100% ownership of your source code, design assets, database, and accounts transfers to you. In writing.\n\n## What Complete Ownership Includes\n\nWhen your project is completed, you receive full administrative access to every single asset:\n- Git repository access containing clean, documented source code\n- High-resolution Figma design files with typography & color tokens\n- Deployment pipeline configurations and server credentials\n- Domain registrar, DNS settings, and SSL certificate ownership\n- Database schemas and API keys\n\n## Why Independent Codebases Win\n\nBuilding on open standard frameworks (React, Next.js, Node, Supabase, Tailwind) ensures your company is never tied to a single agency or developer. Any competent engineer in the world can inspect your repository and start committing code on day one.\n\nIt isn't just about generosity — it's the only ethical way to build software. If the only reason a client stays with an agency is that they physically can't leave, the agency hasn't earned the relationship.",
  },
  {
    slug: "design-systems-that-scale",
    title: "How we build design systems that actually scale",
    excerpt:
      "Why most agency design components break after six months, and how modular UI tokens keep your product consistent as it grows.",
    tags: ["Design", "UI/UX"],
    read_minutes: 6,
    published_at: "2025-12-10",
    cover_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80",
    content:
      "Design systems are often treated as expensive 200-page guidelines that get created once and immediately collect digital dust. In practice, a bloated design system is almost as bad as no system at all.\n\nWhen we design products at Nex Desk, we build light, modular UI tokens in Figma that mirror exact CSS variables in code.\n\n## Tokens First: Typography, Color & Layout\n\nInstead of styling elements ad-hoc, every component references central design tokens:\n- Fluid typography scales (`clamp()`) for flawless desktop & mobile responsiveness\n- Semantic color palettes tailored for light and dark modes\n- Standardized spacing scales ensuring clean alignment\n\n## Bridging Design and Code\n\nWhen Figma component properties map 1-to-1 with React component props, engineering velocity doubles. Designers don't guess pixel values, and developers don't write custom CSS overrides. Your digital product stays consistent even as new features get added.",
  },
  {
    slug: "seo-engineering-for-saas",
    title: "SEO engineering: ranking without keyword stuffing",
    excerpt:
      "Technical structure, automated metadata, clean semantic markup, and server-side performance that search engines reward instantly.",
    tags: ["SEO", "Growth"],
    read_minutes: 7,
    published_at: "2025-11-28",
    cover_url: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=1200&q=80",
    content:
      "Modern search engine optimization isn't about spamming keywords in footer text — it is an engineering discipline. Search engines prioritize websites that render instantly, use proper HTML5 semantic hierarchy, and provide structured data.\n\n## Technical SEO at the Core\n\nWe bake search engine visibility directly into the codebase:\n- Automated OpenGraph and Twitter Card generation for social sharing\n- Structured JSON-LD schema markup for rich search snippets\n- Dynamic XML sitemaps and clean canonical tag generation\n- Semantic HTML5 structure (`<article>`, `<section>`, `<header>`, `<h1>-<h6>`)\n\nBy treating technical SEO as a foundation rather than a plugin, your site starts indexing faster and ranking for high-intent keywords naturally.",
  },
];

export const demoServices: DemoService[] = [
  {
    slug: "custom-web-development",
    title: "Custom Web Application & Website Development",
    category: "Web & Engineering",
    short_desc: "High-performance Next.js & React web applications built for fast loading, clean scalability, and full code ownership.",
    long_desc: "We design and build custom web applications and marketing websites using Next.js, React, and Supabase. Every layout is hand-coded around your actual user flows, avoiding bloated off-the-shelf page builders and unnecessary plugins.\n\nThis service is for growing businesses, startups, and service firms that have outgrown templates and need a fast, reliable web product tailored to their specific business logic and workflows.\n\nYou walk away with a clean, responsive web application hosted on your infrastructure, sub-second page loads, accessible content editing, and complete code ownership with no vendor lock-in.",
    starting_at: 1500,
    currency: "USD",
    features: [
      "Edit content easily without paying developer fees for simple text updates",
      "Pages load in under a second so visitors never bounce due to lag",
      "Clean layouts that work smoothly on phones, tablets, and desktop screens",
      "Full ownership of all source code and assets with no recurring license lock-in",
      "Direct post-launch support and hands-on developer handoff",
    ],
    duration_note: "2–4 weeks delivery",
    is_active: true,
  },
  {
    slug: "mobile-apps",
    title: "iOS & Android Mobile App Development",
    category: "Mobile Apps",
    short_desc: "Cross-platform mobile apps for iOS and Android built with React Native for native feel and store publishing.",
    long_desc: "We build cross-platform mobile applications for iOS and Android using React Native. We handle the full product build, from database integration and offline caching to push notification delivery and store submissions.\n\nThis is for teams launching a mobile product or extending an existing web platform to mobile users without doubling engineering overhead by building two separate native codebases.\n\nYou walk away with a published app on the Apple App Store and Google Play Store, automated update workflows, and clean backend data sync so your mobile app remains responsive even when users are offline.",
    starting_at: 2500,
    currency: "USD",
    features: [
      "Single build that runs on both iPhone and Android, cutting your development cost in half",
      "Send targeted push notifications to re-engage users directly on their phone home screens",
      "App functions smoothly offline and syncs automatically when connection returns",
      "Hassle-free deployment directly to Apple App Store and Google Play accounts",
      "Secure user logins with email, password, and social account authentication",
    ],
    duration_note: "4–6 weeks delivery",
    is_active: true,
  },
  {
    slug: "web-design",
    title: "Web & Product UI/UX Design",
    category: "UI/UX & Design",
    short_desc: "Figma wireframes, interactive prototypes, and modular UI component design for web products.",
    long_desc: "We design interface layouts, interactive prototypes, and design systems in Figma. We map out user journeys and build reusable UI components that make software intuitive to navigate and simple for developers to implement.\n\nPerfect for founders starting a new product, or existing software platforms with confusing user flows that cause customer drop-off and support tickets.\n\nYou walk away with a complete Figma file containing click-through prototypes, mobile and desktop layouts, and a component library that matches production CSS variables for seamless development.",
    starting_at: 1200,
    currency: "USD",
    features: [
      "Test and validate your product idea with clickable prototypes before writing code",
      "Clear layout hierarchy that helps visitors understand your offer and take action",
      "Reusable Figma component library that speeds up future feature additions",
      "Consistent typography and color rules that make your product look established",
      "Developer-ready asset exports so your engineering team builds without guessing",
    ],
    duration_note: "1–2 weeks delivery",
    is_active: true,
  },
  {
    slug: "seo",
    title: "Technical SEO & Search Performance",
    category: "SEO & Marketing",
    short_desc: "Technical SEO engineering, structured schema data, and speed fixes to improve search rankings and indexation.",
    long_desc: "We fix structural, code-level, and metadata issues on your site so search engines can properly crawl, index, and rank your pages. We optimize structured data (JSON-LD), site architecture, meta tags, and page speed.\n\nDesigned for companies with solid products or services whose websites are currently invisible on Google search or losing traffic to technical indexing errors and slow page load speeds.\n\nYou walk away with a search-optimized codebase, corrected Google Search Console indexing errors, rich search snippets, and a clear baseline report tracking your organic impression growth.",
    starting_at: 800,
    currency: "USD",
    features: [
      "Help search engines understand your exact business offerings through schema markup",
      "Eliminate hidden site errors that prevent Google from indexing your valuable pages",
      "Faster page rendering that boosts keyword rankings and user retention",
      "Clean OpenGraph tags so shared links display proper images and titles on social platforms",
      "Transparent monthly reports showing real keyword rankings and organic traffic growth",
    ],
    duration_note: "Ongoing / 2 weeks audit",
    is_active: true,
  },
  {
    slug: "ai-automation",
    title: "AI Integration & Workflow Automation",
    category: "AI & Automation",
    short_desc: "Connect AI models, automated background pipelines, and CRM webhooks to streamline repetitive operations.",
    long_desc: "We connect AI models, data pipelines, and internal tools to automate repetitive manual tasks in your business operations. From automated document processing to intelligent email sorting and CRM updates, we write targeted automation scripts.\n\nBuilt for operational teams spending dozens of hours each week on manual data entry, customer ticket categorization, lead qualification, or document summary tasks.\n\nYou walk away with working background automations integrated into your existing software stack, clear operational logs, and a custom control dashboard where your team can oversee automated jobs.",
    starting_at: 1800,
    currency: "USD",
    features: [
      "Automate repetitive data entry tasks to save your team hours of manual work each week",
      "Extract structured information from customer emails and PDFs directly into your database",
      "Connect your internal tools so customer actions trigger instant downstream updates",
      "Custom admin interface to easily monitor, pause, or adjust automated tasks",
      "Reliable error handling so failed tasks alert your team instead of silently failing",
    ],
    duration_note: "2–3 weeks delivery",
    is_active: true,
  },
  {
    slug: "ecommerce",
    title: "High-Performance E-Commerce Stores",
    category: "E-Commerce",
    short_desc: "Fast custom online storefronts with streamlined checkout, inventory sync, and Stripe payment integration.",
    long_desc: "We build custom, fast online storefronts integrated with Shopify, Stripe, or local payment gateways. We focus on frictionless product discovery, instant page loading, and a clean checkout process.\n\nIdeal for retail brands, direct-to-consumer businesses, and digital merchants looking to increase store conversion rates and escape rigid, sluggish theme templates.\n\nYou walk away with a custom online store, full inventory management synchronization, automated transaction emails, and a simplified checkout flow engineered to maximize completed purchases.",
    starting_at: 2000,
    currency: "USD",
    features: [
      "Instant product page loads that keep shoppers browsing without waiting",
      "Streamlined checkout flow that reduces abandoned carts and increases completed sales",
      "Seamless integration with Stripe, credit card processors, and regional payment options",
      "Automatic inventory sync and customer receipt dispatches",
      "Simple admin dashboard to manage products, order statuses, and discount codes",
    ],
    duration_note: "3–5 weeks delivery",
    is_active: true,
  },
  {
    slug: "brand-identity",
    title: "Brand Identity & Visual Style Guide",
    category: "UI/UX & Design",
    short_desc: "Logomark design, color palettes, typography tokens, and digital brand guideline assets.",
    long_desc: "We create visual brand systems including primary and secondary logomarks, typography rules, color palettes, and digital asset templates. We establish clear rules so your visual presence looks cohesive across web, print, and social channels.\n\nThis service is for new companies establishing their market presence or established businesses undergoing a brand refresh to reflect a more professional, premium positioning.\n\nYou walk away with vector logo files in all formats, a digital brand guidelines PDF, font pairings, color codes for web and print, and ready-to-use social media templates.",
    starting_at: 1000,
    currency: "USD",
    features: [
      "Versatile logo system with scalable vector files for websites, social media, and print",
      "Curated color palette and typography rules that set a professional visual tone",
      "Comprehensive brand guidelines document so anyone on your team can maintain consistency",
      "Ready-to-use social media header and post templates for quick marketing collateral",
      "All master source files delivered in open vector formats for easy future editing",
    ],
    duration_note: "1–2 weeks delivery",
    is_active: true,
  },
  {
    slug: "saas-architecture",
    title: "SaaS & Web Product Engineering",
    category: "Web & Engineering",
    short_desc: "Multi-tenant web application engineering with Stripe subscription billing and role-based user controls.",
    long_desc: "We build multi-tenant web applications with secure account separation, role-based access control, subscription billing, and user management. We construct solid database architecture and API layers designed for steady growth.\n\nDesigned for founders and product teams building software-as-a-service MVPs or internal tools that need multi-user permissions, recurring billing, and scalable database organization.\n\nYou walk away with a fully functional SaaS MVP including customer onboarding flows, Stripe billing management, role-based admin controls, and complete deployment on cloud hosting.",
    starting_at: 3500,
    currency: "USD",
    features: [
      "Secure multi-user database architecture keeping customer data strictly separated",
      "Automated subscription billing, plan upgrades, and invoice receipts via Stripe",
      "Role-based access permissions for admins, team members, and guest users",
      "Self-service customer portal for account settings, password resets, and billing",
      "Comprehensive administrative dashboard to manage users and monitor product metrics",
    ],
    duration_note: "4–8 weeks delivery",
    is_active: true,
  },
  {
    slug: "analytics-cro",
    title: "Web Analytics & Conversion Rate Optimization",
    category: "SEO & Marketing",
    short_desc: "Google Analytics 4 setup, conversion tracking funnels, heatmaps, and user behavior analysis.",
    long_desc: "We configure Google Analytics 4, custom event tracking, conversion funnels, and user interaction heatmaps. We turn raw visitor traffic data into actionable insights so you know exactly where users drop off and how to increase conversions.\n\nBest for marketing managers and business owners with existing website traffic who want to understand visitor behavior and improve contact form inquiries or product sales.\n\nYou walk away with verified event tracking in GA4, custom conversion dashboard views, user flow heatmaps, and a clear list of recommended UX fixes based on real user behavior.",
    starting_at: 700,
    currency: "USD",
    features: [
      "Track button clicks, form submissions, and sales accurately in Google Analytics 4",
      "Identify exact drop-off points in your sign-up or checkout funnel",
      "Visual heatmaps showing where visitors click, scroll, and get confused",
      "Custom dashboard view showing your key business metrics in plain English",
      "Actionable optimization recommendations prioritized by potential revenue impact",
    ],
    duration_note: "1 week delivery",
    is_active: true,
  },
  {
    slug: "api-integrations",
    title: "API & Third-Party System Integration",
    category: "AI & Automation",
    short_desc: "REST/GraphQL API endpoints, webhook background listeners, and CRM payment gateway synchronization.",
    long_desc: "We build custom API connections, webhook processors, and data sync background services between your web platforms and third-party tools like CRMs, payment gateways, accounting software, and marketing platforms.\n\nFor companies whose software systems don't talk to each other, resulting in manual data copying, missed lead notifications, or inconsistent records across tools.\n\nYou walk away with automated data pipelines running reliably between your applications, automatic retry handling for failed network requests, and clear logging for peace of mind.",
    starting_at: 1200,
    currency: "USD",
    features: [
      "Synchronize customer and sales data automatically across your software tools",
      "Instant webhook triggers that update records the second an action occurs",
      "Automatic error logging and retry mechanisms to prevent data loss during downtime",
      "Clean custom REST or GraphQL endpoints tailored to your internal business logic",
      "Thorough API documentation so future developers can easily maintain the connection",
    ],
    duration_note: "1–2 weeks delivery",
    is_active: true,
  },
  {
    slug: "performance-audit",
    title: "Website Speed & Performance Optimization",
    category: "Web & Engineering",
    short_desc: "Eliminate code bloat, optimize images, setup global CDN caching, and fix Core Web Vitals.",
    long_desc: "We audit and optimize website performance by rewriting render-blocking code, optimizing heavy images, setting up global CDN caching, and trimming bloated JavaScript bundles.\n\nWebsite owners whose site loads slowly, fails Google Core Web Vitals standards, or loses mobile visitors due to laggy page rendering and heavy assets.\n\nYou walk away with significantly reduced load times, improved Google Lighthouse performance scores, optimized media assets, and a faster mobile experience for your users.",
    starting_at: 600,
    currency: "USD",
    features: [
      "Dramatically faster initial page rendering that keeps mobile visitors engaged",
      "Compressed web images and modern format delivery without loss of visual quality",
      "Improved Google Core Web Vitals scores that support search engine ranking",
      "Global CDN asset delivery so your site loads quickly for international visitors",
      "Before and after speed report measuring real page load improvements",
    ],
    duration_note: "3–5 days delivery",
    is_active: true,
  },
  {
    slug: "content-copywriting",
    title: "Website Copywriting & Brand Messaging",
    category: "SEO & Marketing",
    short_desc: "Plain, persuasive website headlines, service section messaging, and landing page copywriting.",
    long_desc: "We write clear, persuasive, and jargon-free copy for websites, landing pages, and service offerings. We focus on highlighting your actual client value proposition without corporate hype or artificial buzzwords.\n\nFor business owners whose current site text sounds generic, overly technical, or fails to explain what they do clearly to prospective clients.\n\nYou walk away with complete website text structured into page sections, strong value proposition headlines, natural call-to-action prompts, and content formatted for easy web reading.",
    starting_at: 500,
    currency: "USD",
    features: [
      "Clear headlines that explain your core value proposition within seconds",
      "Jargon-free body copy written in a plain, confident brand voice",
      "Structured page messaging engineered to guide visitors toward contacting you",
      "SEO keyword placement naturally woven into sentences without feeling forced",
      "Ready-to-publish copy documents formatted cleanly for web layout implementation",
    ],
    duration_note: "1 week delivery",
    is_active: true,
  },
  {
    slug: "cloud-devops",
    title: "Cloud Hosting & Deployment Pipeline Setup",
    category: "Web & Engineering",
    short_desc: "Vercel, Supabase, and AWS cloud hosting, automated CI/CD deployments, DNS routing, and SSL setup.",
    long_desc: "We set up production cloud hosting, automated deployment pipelines (CI/CD), domain DNS routing, SSL security, and automated database backups on modern cloud providers like Vercel, Supabase, and AWS.\n\nFor web teams needing a reliable deployment environment where code changes can be previewed safely and deployed to production with zero server setup headaches.\n\nYou walk away with automated deployments linked to your code repository, active SSL encryption, automated database backup schedules, and monitoring alerts for peace of mind.",
    starting_at: 1500,
    currency: "USD",
    features: [
      "Automated deployments whenever you push code changes to GitHub",
      "Staging environments to test new features safely before going live to customers",
      "Automated daily database backups so your application data is always safe",
      "Proper SSL setup and DNS configuration for custom domain security",
      "Monitoring setup to alert team leads immediately if server errors occur",
    ],
    duration_note: "1–2 weeks delivery",
    is_active: true,
  },
  {
    slug: "design-system-audit",
    title: "Design System & UI Component Audit",
    category: "UI/UX & Design",
    short_desc: "Audit visual interface components and consolidate styling tokens into Figma and Tailwind libraries.",
    long_desc: "We review your visual interface components and code repository to consolidate fragmented styles into a cohesive, reusable design system in Figma and React/Tailwind code.\n\nIdeal for product teams building software with inconsistent UI patterns, duplicate styling code, or visual mismatch between design files and the live site.\n\nYou walk away with a cleaned-up component library, mapped UI tokens (colors, spacing, typography), and documented guidelines that make adding new features simple and consistent.",
    starting_at: 900,
    currency: "USD",
    features: [
      "Eliminate duplicate UI code and inconsistent button styles across your app",
      "Figma design tokens that match live CSS variables line for line",
      "Faster front-end development time when building future application screens",
      "Improved accessibility contrast and font readability across all devices",
      "Clear component documentation so your team builds consistent interfaces",
    ],
    duration_note: "1 week delivery",
    is_active: true,
  },
  {
    slug: "ongoing-retainer",
    title: "Monthly Engineering & Design Support",
    category: "Support & Retainers",
    short_desc: "Dedicated monthly developer and designer hours for continuous updates, maintenance, and features.",
    long_desc: "We provide a dedicated allocation of engineering and design hours each month for ongoing site updates, bug fixes, feature iterations, and performance monitoring.\n\nFor business owners and product leads who need reliable technical support and steady software improvements without hiring full-time internal engineering staff.\n\nYou walk away with a dependable development partner on standby, guaranteed monthly development turnaround, transparent hour tracking, and priority response for critical issues.",
    starting_at: 2500,
    currency: "USD",
    features: [
      "Dedicated developer hours reserved specifically for your project each month",
      "Direct access to senior engineers for quick feature updates and advice",
      "Routine security updates, package maintenance, and uptime monitoring",
      "Flexible allocation of hours between design, development, and technical SEO",
      "Transparent monthly status summaries detailing completed work and hours used",
    ],
    duration_note: "Monthly Retainer",
    is_active: true,
  },
  {
    slug: "security-compliance",
    title: "Database & API Security Audit",
    category: "Support & Retainers",
    short_desc: "Security audit of Supabase Row Level Security (RLS) policies, authentication endpoints, and API permissions.",
    long_desc: "We review your database architecture, Row Level Security (RLS) policies, authentication endpoints, and API authorization rules to ensure user data is properly restricted and protected.\n\nBuilt for SaaS founders and business applications handling sensitive customer data or multi-tenant database records where unauthorized access must be prevented.\n\nYou walk away with audited RLS policies, secured database functions, fixed API endpoint vulnerabilities, and a written report detailing implemented security fixes.",
    starting_at: 1100,
    currency: "USD",
    features: [
      "Strict Row Level Security policies ensuring users can only access their own data",
      "Thorough check of API endpoints and database permissions to prevent data leaks",
      "Review of authentication pipelines, token storage, and session security",
      "Immediate remediation of identified permission flaws and configuration risks",
      "Comprehensive summary report documenting all security rules and access controls",
    ],
    duration_note: "1 week delivery",
    is_active: true,
  },
];

export const demoQuotes: DemoQuote[] = [
  { client_name: "Ayesha Khan", role: "Founder", company: "Lumen Studio", rating: 5,
    quote: "They shipped in four weeks what two previous agencies couldn't in six months. The staging link from day one meant no surprises." },
  { client_name: "Daniel Reeve", role: "CEO", company: "Northwind", rating: 5,
    quote: "The written scope saved us. Everyone knew exactly what was being built and what it cost. No arguments at the end." },
  { client_name: "Priya Nair", role: "Head of Growth", company: "Vertex", rating: 5,
    quote: "Our organic traffic tripled in three months. They actually explained what they were doing instead of hiding behind jargon." },
  { client_name: "Marco Bianchi", role: "Owner", company: "Práctica", rating: 5,
    quote: "The receipt and agreement PDFs made us look far bigger than we are. Clients take us seriously now." },
  { client_name: "Sana Malik", role: "Director", company: "Kavi", rating: 5,
    quote: "Weekly progress emails I never had to ask for. I always knew where the project stood." },
  { client_name: "Tom Alvarez", role: "Co-founder", company: "Orbit", rating: 5,
    quote: "We own everything — code, files, accounts. No lock-in, no hostage situation. Rare in this business." },
  { client_name: "Hina Farooq", role: "Marketing Lead", company: "Fathom", rating: 5,
    quote: "The ad campaigns hit the cost-per-lead target they promised in the first month. Straight talk, real numbers." },
];
