"use client";

import { useEffect, useRef } from "react";
import { gsap } from "gsap";
import { avatar } from "@/lib/images";

/* eslint-disable @typescript-eslint/no-explicit-any */

type Quote = {
  client_name: string;
  role?: string | null;
  company?: string | null;
  quote: string;
  rating?: number | null;
};

/**
 * A testimonial *wall*, not a carousel. One large featured quote on the left,
 * and on the right two columns of cards drifting slowly in opposite directions.
 * No arrows, no dots, nothing to click — it just moves. Pauses on hover so
 * anyone can stop and read. Falls back to a static grid on reduced motion.
 *
 * Avatars are generated by DiceBear from each person's name, so they're
 * consistent and distinctive without needing real photos.
 */
export default function TestimonialWall({ quotes }: { quotes: Quote[] }) {
  const ref = useRef<HTMLDivElement>(null);

  // Guarantee enough cards to fill two scrolling columns.
  const filled = quotes.length >= 6 ? quotes : [...quotes, ...quotes, ...quotes].slice(0, Math.max(6, quotes.length));
  const featured = filled[0];
  const rest = filled.slice(1);
  const colA = rest.filter((_, i) => i % 2 === 0);
  const colB = rest.filter((_, i) => i % 2 === 1);

  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const ctx = gsap.context(() => {
      gsap.to(".tw-col-up .tw-track", { yPercent: -50, duration: 26, ease: "none", repeat: -1 });
      gsap.fromTo(".tw-col-down .tw-track", { yPercent: -50 }, { yPercent: 0, duration: 26, ease: "none", repeat: -1 });
    }, ref);
    return () => ctx.revert();
  }, []);

  if (!featured) return null;

  return (
    <section ref={ref} className="shell py-28">
      <p className="drawer-label">In their words</p>

      <div className="mt-10 grid gap-6 lg:grid-cols-[1fr_1fr]">
        {/* featured */}
        <figure className="flex flex-col justify-between">
          <div>
            <div className="flex gap-1 text-lime-400">
              {Array.from({ length: featured.rating ?? 5 }).map((_, i) => <span key={i}>★</span>)}
            </div>
            <blockquote className="mt-6 text-[clamp(1.5rem,3vw,2.25rem)] leading-[1.25] tracking-tight"
              style={{ fontFamily: "var(--font-display)" }}>
              &ldquo;{featured.quote}&rdquo;
            </blockquote>
          </div>
          <figcaption className="mt-10 flex items-center gap-4">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={avatar(featured.client_name)} alt="" className="h-12 w-12 rounded-full border border-ink-600" />
            <div>
              <p className="font-medium">{featured.client_name}</p>
              <p className="mono-tag">{[featured.role, featured.company].filter(Boolean).join(" · ")}</p>
            </div>
          </figcaption>
        </figure>

        {/* two drifting columns */}
        <div className="relative grid h-[520px] grid-cols-2 gap-4 overflow-hidden [mask-image:linear-gradient(to_bottom,transparent,#000_12%,#000_88%,transparent)]">
          <Column cards={colA} dir="up" />
          <Column cards={colB} dir="down" />
        </div>
      </div>
    </section>
  );
}

function Column({ cards, dir }: { cards: Quote[]; dir: "up" | "down" }) {
  return (
    <div className={`tw-col-${dir}`}>
      <div className="tw-track space-y-4">
        {[...cards, ...cards].map((q, i) => (
          <figure key={i} className="card p-5 transition-colors hover:border-lime-400/30">
            <p className="text-sm leading-relaxed text-bone-200">&ldquo;{q.quote}&rdquo;</p>
            <figcaption className="mt-4 flex items-center gap-2.5 border-t border-ink-600 pt-4">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={avatar(q.client_name)} alt="" className="h-8 w-8 rounded-full border border-ink-600" />
              <div className="min-w-0">
                <p className="truncate text-xs font-medium">{q.client_name}</p>
                <p className="mono-tag truncate text-[0.5625rem]">{q.company ?? q.role ?? ""}</p>
              </div>
            </figcaption>
          </figure>
        ))}
      </div>
    </div>
  );
}
